

version: "0.1"
services:
  app:
    build:
      args:
        user: sira
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sira
    container_name: sira-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8001:8001
    volumes:
      - ./:/var/www
    networks:
      - sira

  db:
    image: mysql:8.3.0
    container_name: sira-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - sira

  nginx:
      image: nginx:latest
      container_name: sira-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./nginx:/etc/nginx/conf.d
      networks:
        - sira

networks:
  sira:
    driver: bridge


